stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
    - ./scripts/ci-cleanup.sh
  cache:
    paths:
      - layers

qemux86:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemux86-64:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemuarm:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemuarm64:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemumppc:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemumips64:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemuriscv64:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-build-image

qemux86-64-tpm:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-tpm-image

qemux86-64-tpm2:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-tpm2-image

qemuarm64-tpm2:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME security-tpm2-image


qemux86-ima:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME integrity-image-minimal

qemux86-64-ima:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME integrity-image-minimal

qemuarm64-iam:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME integrity-image-minimal

